# Generated by Django 5.1.1 on 2024-09-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
